apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-database-pvc
  labels:
    k8s-app: pg-database
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
