apiVersion: v1
kind: ConfigMap
metadata:
  name: account-reactive-cm
  namespace: default
  labels:
    k8s-app: account-reactive
data:
  management.endpoint.shutdown.enabled: "true"
  management.endpoints.web.exposure.include: '*'
  server.port: "8080"
  spring.r2dbc.url: r2dbc:postgresql://postgres-service:5432/account
  spring.r2dbc.username: postgres
  spring.sql.init.mode: always
  spring.jackson.serialization.INDENT_OUTPUT: "true"
  server.error.include-message: always
  logging.level.root: INFO
