apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-server
  labels:
    k8s-app: recipe-server
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: recipe-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        k8s-app: recipe-server
    spec:
      containers:
      - image: wisskirchenj/recipe-server:0.3.0-SNAPSHOT
        imagePullPolicy: Always
        name: recipe-server
        ports:
        - containerPort: 8080
          protocol: TCP
        envFrom:
        - configMapRef:
            name: recipe-server-cm
        env:
        - name: spring.datasource.password
          valueFrom:
            secretKeyRef:
              name: postgres-user-secret
              key: password
        resources: {}
      restartPolicy: Always
status: {}
