apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorization-gateway
  labels:
    k8s-app: authorization-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: authorization-gateway
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        k8s-app: authorization-gateway
    spec:
      containers:
      - image: wisskirchenj/authorization-server:0.1.6-SNAPSHOT
        name: authorization-server
        ports:
        - containerPort: 5050
          protocol: TCP
        envFrom:
        - configMapRef:
            name: authorization-server-cm
        env:
        - name: spring.datasource.password
          valueFrom:
            secretKeyRef:
              name: postgres-user-secret
              key: password
        - name: spring.security.oauth2.client.registration.spring.client-secret
          valueFrom:
            secretKeyRef:
              name: authclient-gateway-secret
              key: bcrypt
        resources: {}
        imagePullPolicy: Always
      - image: wisskirchenj/gateway:latest
        name: gateway
        ports:
        - containerPort: 5500
          protocol: TCP
        envFrom:
        - configMapRef:
            name: gateway-cm
        env:
        - name: spring.datasource.password
          valueFrom:
            secretKeyRef:
              name: postgres-user-secret
              key: password
        - name: spring.security.oauth2.authorizationserver.client.client-1.registration.client-secret
          valueFrom:
            secretKeyRef:
              name: authclient-gateway-secret
              key: password
        resources: {}
        imagePullPolicy: Always
      restartPolicy: Always
status: {}
