apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recipe-server-pvc
  labels:
    k8s-app: recipe-server
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
