apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    k8s-app: pg-database
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
