apiVersion: v1
kind: Service
metadata:
  name: recipe-service
  labels:
    k8s-app: recipe-server
spec:
  ports:
  - name: 9090-tcp
    port: 9090
    protocol: TCP
    targetPort: 8080
  selector:
    k8s-app: recipe-server
  type: LoadBalancer
status:
  loadBalancer: {}
