apiVersion: v1
kind: Service
metadata:
  name: code-sharing-service
spec:
  ports:
  - name: 9000-tcp
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    k8s-app: code-sharing-platform
  type: LoadBalancer
status:
  loadBalancer: {}
