apiVersion: v1
kind: Service
metadata:
  name: authorization-service
  labels:
    k8s-app: authorization-server
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 5050-tcp
    port: 5050
    protocol: TCP
    targetPort: 5050
  selector:
    k8s-app: authorization-server
  sessionAffinity: None
  type: ClusterIP