apiVersion: v1
kind: Service
metadata:
  name: account-service
  labels:
    k8s-app: account-reactive
  namespace: default
spec:
  ports:
  - name: 5080-tcp
    port: 5080
    protocol: TCP
    targetPort: 5080
  selector:
    k8s-app: account-reactive
  type: LoadBalancer
