apiVersion: v1
kind: Service
metadata:
  name: recipe-service
  labels:
    k8s-app: recipe-server
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: 9090-tcp
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    k8s-app: recipe-server
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
