apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    k8s-app: gateway
  namespace: default
spec:
  ports:
  - name: 5500-tcp
    port: 5500
    protocol: TCP
    targetPort: 5500
  selector:
    k8s-app: gateway
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}