apiVersion: v1
kind: Service
metadata:
  name: code-sharing-service
  labels:
    k8s-app: code-sharing-platform
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: 9000-tcp
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    k8s-app: code-sharing-platform
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
