apiVersion: v1
kind: Service
metadata:
  name: account-service
  labels:
    k8s-app: account-reactive
  namespace: default
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    k8s-app: account-reactive
  type: LoadBalancer
  