apiVersion: v1
kind: Service
metadata:
  name: quiz-engine-service
  labels:
    k8s-app: web-quiz-engine
spec:
  ports:
  - name: 9009-tcp
    port: 9009
    protocol: TCP
    targetPort: 9009
  selector:
    k8s-app: web-quiz-engine
  type: LoadBalancer
status:
  loadBalancer: {}