apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    k8s-app: gateway
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: 5500
    protocol: TCP
    targetPort: 5500
  selector:
    k8s-app: gateway
  type: LoadBalancer
