apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  labels:
    k8s-app: pgadmin
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
  selector:
    k8s-app: pgadmin
  type: NodePort